package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/epmon-dev/epmon/internal/config"
	"gopkg.in/yaml.v3"
)

func TestSecretRef(t *testing.T) {
	for in, want := range map[string]string{
		"$TOKEN":         "${TOKEN}",
		"Bearer $TOKEN":  "Bearer ${TOKEN}",
		"${TOKEN}":       "${TOKEN}",
		"${T:-fallback}": "${T:-fallback}",
		"$$":             "$$",
		"costs $$5":      "costs $$5",
		"plain":          "plain",
		"Bearer ${T} $U": "Bearer ${T} ${U}",
		"trailing$":      "trailing$",
		"$9bad $GOOD":    "$9bad ${GOOD}",
	} {
		if got := secretRef(in); got != want {
			t.Errorf("secretRef(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestParseExpect(t *testing.T) {
	single, err := parseExpect("200")
	if err != nil {
		t.Fatalf("parseExpect(200): %v", err)
	}
	if single.Tag != "!!int" || single.Value != "200" {
		t.Errorf("single int emits %s %q, want scalar 200", single.Tag, single.Value)
	}
	class, err := parseExpect("2xx")
	if err != nil {
		t.Fatalf("parseExpect(2xx): %v", err)
	}
	if class.Tag != "!!str" || class.Value != "2xx" {
		t.Errorf("single class emits %s %q, want scalar 2xx", class.Tag, class.Value)
	}
	multi, err := parseExpect("200, 301")
	if err != nil {
		t.Fatalf("parseExpect(200, 301): %v", err)
	}
	if multi.Kind != yaml.SequenceNode {
		t.Errorf("multi emits kind %v, want sequence", multi.Kind)
	}
	for _, bad := range []string{"", "bogus", "99", "200, bogus", `"200"`} {
		if _, err := parseExpect(bad); err == nil {
			t.Errorf("parseExpect(%q) = nil error, want failure", bad)
		}
	}
}

func TestInitFromFlagsRejects(t *testing.T) {
	if _, err := initFromFlags("o.yaml", ":8080", "e.db", 90, "60s", "10s", 1, nil); err == nil {
		t.Error("zero services accepted, want failure")
	}
	for _, raw := range []string{"nourl", "=https://x.example.com", "id=", "api=https://a.example.com;bogus=1"} {
		if _, err := initFromFlags("o.yaml", ":8080", "e.db", 90, "60s", "10s", 1, serviceFlag{raw}); err == nil {
			t.Errorf("service %q accepted, want failure", raw)
		}
	}
}

// TestInitNonInteractiveGolden drives flags through rendering, asserts the
// exact file, and proves the gate by loading it with the real loader.
func TestInitNonInteractiveGolden(t *testing.T) {
	out := filepath.Join(t.TempDir(), "epmon.yaml")
	doc, err := initFromFlags(out, ":8080", "epmon.db", 90, "60s", "10s", 1, serviceFlag{
		"api=https://api.example.com/healthz;interval=30s;expect=200,301",
		"web=https://example.com",
	})
	if err != nil {
		t.Fatalf("initFromFlags: %v", err)
	}
	if err := writeInitDoc(doc, false, io.Discard); err != nil {
		t.Fatalf("writeInitDoc: %v", err)
	}
	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	want := "# Generated by `epmon init` — edit freely, then validate:\n" +
		"#   epmon validate --config " + out + "\n" +
		"server:\n" +
		"  # epmon API listen address.\n" +
		"  listen: :8080\n" +
		"database:\n" +
		"  # Storage: sqlite file plus history retention.\n" +
		"  driver: sqlite\n" +
		"  dsn: epmon.db\n" +
		"  retention_days: 90\n" +
		"probes:\n" +
		"  # Fleet probe defaults; services inherit unless overridden.\n" +
		"  default_interval: 60s\n" +
		"  default_timeout: 10s\n" +
		"  failure_threshold: 1\n" +
		"services:\n" +
		"  - id: api\n" +
		"    url: https://api.example.com/healthz\n" +
		"    interval: 30s\n" +
		"    expect_status: [200, 301]\n" +
		"  - id: web\n" +
		"    url: https://example.com\n" +
		"    expect_status: 200\n"
	if string(raw) != want {
		t.Errorf("golden mismatch:\n got:\n%s\nwant:\n%s", raw, want)
	}
	if _, err := config.Load(out); err != nil {
		t.Errorf("generated file fails the real loader: %v", err)
	}
}

func TestInitRefusesOverwrite(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "epmon.yaml")
	if err := os.WriteFile(out, []byte("existing: true\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	doc, err := initFromFlags(out, ":8080", "e.db", 90, "60s", "10s", 1,
		serviceFlag{"a=https://a.example.com"})
	if err != nil {
		t.Fatal(err)
	}
	if err := writeInitDoc(doc, false, io.Discard); err == nil {
		t.Fatal("overwrite without --force accepted")
	}
	raw, _ := os.ReadFile(out)
	if string(raw) != "existing: true\n" {
		t.Error("existing file touched despite refusal")
	}
	if err := writeInitDoc(doc, true, io.Discard); err != nil {
		t.Fatalf("--force write: %v", err)
	}
	if _, err := config.Load(out); err != nil {
		t.Errorf("forced file fails the loader: %v", err)
	}
}

// TestInitGateLeavesNothingBehind feeds an un-runnable document (bad URL
// passes the fast checks but the loader rejects it) and asserts neither
// the destination nor temp files appear.
func TestInitGateLeavesNothingBehind(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "epmon.yaml")
	doc := &initDoc{
		output: out, listen: ":8080", dsn: "e.db", retention: 90,
		defInterval: "60s", defTimeout: "10s", threshold: 1,
		services: []initService{{id: "a", url: "https://a.example.com", expect: "200"}},
	}
	doc.services[0].interval = "1s" // parses, but loader demands >= 5s
	if err := writeInitDoc(doc, false, io.Discard); err == nil {
		t.Fatal("invalid document written")
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			names = append(names, e.Name())
		}
		t.Errorf("leftovers in %s: %v", dir, names)
	}
}

const interactiveInput = `
db.sqlite




api
API
https://api.example.com/healthz
30s

2xx

Authorization: Bearer $TOKEN

web

https://example.com






`

func TestInitInteractiveGolden(t *testing.T) {
	out := filepath.Join(t.TempDir(), "epmon.yaml")
	doc, err := initInteractive(strings.NewReader(interactiveInput), io.Discard, out)
	if err != nil {
		t.Fatalf("initInteractive: %v", err)
	}
	if len(doc.services) != 2 || doc.services[0].id != "api" || doc.dsn != "db.sqlite" {
		t.Fatalf("unexpected doc: %+v", doc)
	}
	if got := doc.services[0].headers[0]; got != [2]string{"Authorization", "Bearer ${TOKEN}"} {
		t.Errorf("header = %v, want secret reference", got)
	}
	if err := writeInitDoc(doc, false, io.Discard); err != nil {
		t.Fatalf("writeInitDoc: %v", err)
	}
	// The stubbed gate must hold with the real variable present too.
	t.Setenv("TOKEN", "secret")
	if _, err := config.Load(out); err != nil {
		t.Errorf("generated file fails the real loader: %v", err)
	}
}

func TestInitInteractiveAbort(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "epmon.yaml")
	// EOF mid-service: no file may appear.
	if _, err := initInteractive(strings.NewReader("\n\ndb.sqlite\n\n\n\n\napi\n"), io.Discard, out); err == nil {
		t.Fatal("EOF accepted, want abort")
	}
	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Error("file written despite abort")
	}
	// Empty id up front re-prompts instead of producing zero services.
	doc, err := initInteractive(strings.NewReader("\ndb.sqlite\n\n\n\n\n\nweb\n\nhttps://example.com\n\n\n\n\n\n\n"), io.Discard, out)
	if err != nil {
		t.Fatalf("empty-first-id run: %v", err)
	}
	if len(doc.services) != 1 {
		t.Errorf("got %d services, want 1", len(doc.services))
	}
}

func TestInitCommandUsage(t *testing.T) {
	if code := initCommand([]string{"positional"}, strings.NewReader(""), io.Discard, io.Discard); code != exitUsage {
		t.Errorf("positional args = %d, want %d", code, exitUsage)
	}
	if code := initCommand([]string{"--service", "a=https://a.example.com"}, strings.NewReader(""), io.Discard, io.Discard); code != exitUsage {
		t.Errorf("--service without --non-interactive = %d, want %d", code, exitUsage)
	}
}

func TestInitCommandNonInteractive(t *testing.T) {
	out := filepath.Join(t.TempDir(), "epmon.yaml")
	code := initCommand([]string{
		"--non-interactive", "--output", out,
		"--service", "a=https://a.example.com",
	}, strings.NewReader(""), io.Discard, io.Discard)
	if code != exitOK {
		t.Fatalf("initCommand = %d, want %d", code, exitOK)
	}
	if _, err := config.Load(out); err != nil {
		t.Errorf("generated file fails the real loader: %v", err)
	}
}
